src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Entity\Produit;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CommandeRepository;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Membre $membre = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Produit $produit = null;

    #[ORM\Column]
    private ?int $quantite = null;

    #[ORM\Column]
    private ?int $montant = null;

    #[ORM\Column(length: 255)]
    private ?string $etat = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMembre(): ?Membre
    {
        return $this->membre;
    }

    public function setMembre(?Membre $membre): static
    {
        $this->membre = $membre;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): static
    {
        $this->produit = $produit;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): static
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getMontant(): ?int
    {
        return $this->montant;
    }

    public function setMontant(int $montant): static
    {
        $this->montant = $montant;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): static
    {
        $this->etat = $etat;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }
}

templates/commandes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes commandes{% endblock %}

{% block body %}
    <h1 class="edit-h1 text-center my-3">Mes commandes</h1>
    {% if app.user.commandes is empty %}
        <p>Aucune commande trouvée.</p>
    {% else %}
    <div class="d-flex justify-content-center">
        <table class="table table-striped-columns mt-5 w-75 table-dark text-dark">
            <thead>
                <tr>
                    <th>ID Commande</th>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Titre du produit</th>
                    <th>Description</th>
                    <th>Couleur</th>
                    <th>Taille</th>
                    <th>Quantité</th>
                    <th>Montant</th>
                    <th>État</th>
                    <th>Date d'enregistrement</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
                {% for commande in app.user.commandes %}
    <tr>
        <td>{{ commande.id }}</td>
        <td>{{ commande.membre.nom }}</td>
        <td>{{ commande.membre.prenom }}</td>
            <td>{{ commande.produit.titre }}</td>
            <td>{{ commande.produit.description|raw }}</td>
            <td>{{ commande.produit.couleur }}</td>
            <td>{{ commande.produit.taille }}</td>
        <td>{{ commande.quantite }}</td>
        <td>{{ commande.montant }}</td>
        <td>{{ commande.etat }}</td>
        <td>{{ commande.dateEnregistrement|date('Y-m-d H:i:s') }}</td>
        
        <td><a href="{{ path('cart_commande_delete', {'id': commande.id}) }}" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette commande ?')" class="text-primary  me-3" style="font-size: 1.4rem; "><i class="fa fa-trash"></i></a></td>
 
    </tr>
{% endfor %}
            </tbody>
        </table>
        </div>
    {% endif %}
{% endblock %}